pipeline {
    agent any

    environment {

        DOCKER_REGISTRY = 'aichanciri'
        DOCKER_IMAGE = 'devopsfront'
    }

    stages {
        stage('Checkout') {
            steps {
                // Pull the code from the specified branch of your GitHub repository
                git branch: 'AichaNciri_5Arctic3_G4',
                    url: 'https://github.com/devopsproject976/devops.git',
                    credentialsId: 'dev' // Use the credentials ID you created
            }
        }



        stage('Docker Build') {
            steps {
                script {
                    // Build Docker image using the Dockerfile
                    dir('Frontend') {
                        sh "docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest ."
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    // Use Docker Hub credentials
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}'
                       sh 'docker push aichanciri/devopsfront'
                    }
                }
            }
        }
    }

    post {

        success {

            echo 'Build and tests succeeded!'
        }
        failure {
            echo 'Build or test failed.'
        }
    }
}
