version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring:
    image: medaminetrabelsi/devopsback:latest  # Image depuis Docker Hub
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  angular:
    image: medaminetrabelsi/devopsfront:latest
    ports:
      - "4200:4200"
    depends_on:
      - spring

volumes:
  mysql-data: {}

